scalar:
  enabled: false

spring:
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
      circuitbreaker:
        enabled: true
  application:
    name: 'furrify-storage-service'
  main:
      web-application-type: servlet
  jpa:
    open-in-view: false
  profiles:
    active: prod
server:
  port: 8081


springdoc:
  api-docs:
    version: openapi_3_0
